title: Default

#status:
#  draft: true
#  listed: true

#options:
#  changeSlug: false
#  delete: false

# options:
#   url: false
#   status: false
#   delete: false

columns:
  - width: 2/3  
    sections:
      infos:
        type: fields
        fields:
          FirstName:
            label: Prenom
            type: text
            translate: false
            width: 1/2
          LastName:
            label: Nom
            type: text
            translate: false
            width: 1/2
          # displayname: 
          #   label: Nom Affiché
          #   type: structure
          #   min: 1
          #   max: 1
          #   columns: 
          #     FirstName: 
          #       width: 1/3     
          #     LastName: 
          #       width: 1/3
          #     LastName2: 
          #       width: 1/3
          #   fields: 
          #     FirstName: 
          #       label: Prénom
          #       type: text
          #       width: 1/3
          #     LastName: 
          #       label: Nom
          #       type: text
          #       width: 1/3
          #     LastName2: 
          #       label: Nom
          #       type: text
          #       width: 1/3
          position:
            type: text
          about:
            label: About
            type: textarea
            size: medium
            
  - width: 1/3
    fields:
      linkedin:
        type: url 
        translate: false
      twitter:
        type: url 
        translate: false
      angelist:
        type: url
        translate: false


            

  # right:
  #   width: 1/4
  #   sections:
  #     medias:
  #       type: fields
  #       fields:
  #         avatar:
  #           extends: sections/avatar